# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d67e54afd165cc8d622193b92ecc4f2d6ccf3f43cdbd83af88307907d8b5e1bcff64d165ecf3269fdd3a0711e8b90895bcf00ddc20dee8090ff318a2f4f31de

test:
  secret_key_base: 18c4f03fc184d728548a9c077d8b92a968f2f654fcc5771340ece9d9fb3461d05b29612ac1517d785aceda3fbd60a7d26a2d6717dc85e4710d1c995b7b10ff99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
